image: alpine

stages:
  - build
  - publish

build-linux:
  stage: build
  image: rust:latest
  script:
    - export SOURCE_DIR="$(pwd)"
    - cd /
    - echo "and of course the default package registry has some old-ass version of cmake"
    - wget https://github.com/Kitware/CMake/releases/download/v3.16.7/cmake-3.16.7-Linux-x86_64.tar.gz
    - tar -xzf cmake-3.16.7-Linux-x86_64.tar.gz
    - export PATH="$PATH:/cmake-3.16.7-Linux-x86_64/bin"
    - apt update
    - apt -y install llvm-7 libxrandr-dev libxinerama-dev libxcursor-dev libasound-dev
    - export LLVM_SYS_70_PREFIX=/usr/bin/llvm-7/
    - cd $SOURCE_DIR
    - cd frontends/juce/
    - git submodule init
    - git submodule update
    - ./build_linux.sh release
  only:
    - master
    - merge_requests
  artifacts:
    expire_in: 2h
    paths:
      - frontends/juce/artifacts/

build-windows:
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: build
  script:
    - echo "this script fills me with pain"
    - echo "chocolatey's llvm package is missing a binary only available when compiling from source"
    - echo "llvmenv refuses to build and causes an out of memory error or something"
    - echo "so I spent two days figuring out how to compile llvm myself and hosted the build artifacts on another gitlab repo"
    - git clone "https://gitlab.com/Code_Cube/llvm-win.git" "C:\LLVM"
    - $Env:LLVM_SYS_70_PREFIX="C:\LLVM\"
    - echo "llvm-config is compiled with mingw and requires some dlls it comes with."
    - choco install mingw -y
    - echo "Reload the path because I don't trust anything."
    - $Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - echo $Env:Path
    - echo "Test that llvm works."
    - C:\LLVM\bin\llvm-config.exe --version
    - choco install cmake.install -y --version=3.16.7 --installargs 'ADD_CMAKE_TO_PATH=User'
    - refreshenv
    - echo "Despite the fact that chocolatey promises that refreshenv works, it in fact does absolutely nothing and is useless"
    - $Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - cmake --version
    - choco install rust --version=1.41.0 -y
    - choco install windows-sdk-10.0 -y
    - cd frontends/juce/
    - git submodule init
    - git submodule update
    - .\build_win
  only:
    - master
    - merge_requests
  artifacts:
    expire_in: 2h
    paths:
      - frontends/juce/artifacts/

build-website:
  stage: build
  image: alpine
  script:
    - cd docs/website
    - mkdir artifacts
    - cp -r src/* artifacts/
  only:
    - master
  artifacts:
    expire_in: 2h
    paths:
      - docs/website/artifacts/

pages:
  stage: publish
  image: alpine
  script:
    - mkdir public
    - mv docs/website/artifacts/* public/
    - mkdir public/builds/
    - mv frontends/juce/artifacts/* public/builds/
  only:
    - master
  artifacts:
    paths:
      - public
