image: alpine

stages:
  - build
  - publish

build-linux:
  stage: build
  image: rust:latest
  script:
    - git submodule init
    - git submodule update
    - export SOURCE_DIR="$(pwd)"
    - cd /
    - echo "and of course the default package registry has some old-ass version of cmake"
    - wget https://github.com/Kitware/CMake/releases/download/v3.16.7/cmake-3.16.7-Linux-x86_64.tar.gz
    - tar -xzf cmake-3.16.7-Linux-x86_64.tar.gz
    - export PATH="$PATH:/cmake-3.16.7-Linux-x86_64/bin"
    - apt update
    - apt -y install llvm-7 libxrandr-dev libxinerama-dev libxcursor-dev libasound-dev extra-cmake-modules
    - export LLVM_SYS_70_PREFIX=/usr/bin/llvm-7/
    - cd $SOURCE_DIR
    - ./build.py juce_frontend --release
  only:
    - master
    - merge_requests
  artifacts:
    expire_in: 2h
    paths:
      - artifacts/bin/

build-windows:
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: build
  script:
    - echo "Required for build script."
    - choco install python3 -y
    - python3 --help
    - git submodule init
    - git submodule update
    - echo "this script fills me with pain"
    - echo "chocolatey's llvm package is missing a binary only available when compiling from source"
    - echo "llvmenv refuses to build and causes an out of memory error or something"
    - echo "so I spent two days figuring out how to compile llvm myself and hosted the build artifacts on another gitlab repo"
    - git clone "https://gitlab.com/Code_Cube/llvm-win.git" "C:\LLVM"
    - $Env:LLVM_SYS_70_PREFIX="C:\LLVM\"
    - echo "Some of the cargo libs still require gcc to compile."
    - choco install mingw -y
    - echo "Reload the path because I don't trust anything."
    - $Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - echo $Env:Path
    - echo "Test that llvm works."
    - C:\LLVM\bin\llvm-config.exe --version
    - choco install cmake.install -y --version=3.16.7 --installargs 'ADD_CMAKE_TO_PATH=User'
    - refreshenv
    - echo "Despite the fact that chocolatey promises that refreshenv works, it in fact does absolutely nothing and is useless"
    - $Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - choco install rust-ms --version=1.44.1 -y
    - choco install windows-sdk-10.0 -y
    - python3 build.py juce_frontend --release
  only:
    - master
    - merge_requests
  artifacts:
    expire_in: 2h
    paths:
      - artifacts/bin/

build-website:
  stage: build
  image: alpine
  script:
    - mkdir -p artifacts/website/
    - cp -r docs/website/src/* artifacts/website/
  only:
    - master
  artifacts:
    expire_in: 2h
    paths:
      - artifacts/website/

pages:
  stage: publish
  image: alpine
  script:
    - mkdir public
    - mv artifacts/website/* public/
    - mkdir -p public/builds/
    - mv artifacts/bin/* public/builds/
  only:
    - master
  artifacts:
    paths:
      - public
