[package]
name = "audiobench-clib"
version = "0.1.0"
authors = ["Code_Cube <therealcodecube@gmail.com>"]
edition = "2018"

[lib]
name = "audiobench_clib"
crate-type = ["staticlib"]

[dependencies]
audiobench = { path = "../audiobench" }
